#!/usr/bin/env python3
"""Export curated quic-utls profiles → dist/export/ (lab artifact for future product sync).

SoT is quic-utls-profile-v1 (emit recipe), NOT raw initials/*.bin.
Does not touch sing-box / CI — only prepares dist/export/.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

from quic_utls_lib import (
    CATALOG_FORMAT,
    PROFILE_FORMAT,
    family_of,
    is_dialable,
    iter_curated_profiles,
    write_json,
)

ROOT = Path(__file__).resolve().parents[1]
CATALOG_DIR = ROOT / "catalog" / "utls"
EXPORT_DIR = ROOT / "dist" / "export"


def sha16_bytes(b: bytes) -> str:
    return "sha256:" + hashlib.sha256(b).hexdigest()[:16]


def load_curated() -> list[dict]:
    return [doc for _, doc in iter_curated_profiles(CATALOG_DIR)]


def write_emit_templates(docs: list[dict], path: Path) -> None:
    """Legacy sketch file — generated from curated catalog (no second SoT)."""
    out: dict = {
        "_comment": (
            "GENERATED by export_dist.py from catalog/utls/*.json. "
            "Do not edit by hand. See docs/UTLS_PROFILE.md."
        )
    }
    for doc in docs:
        short = doc["short"]
        emit = doc.get("emit") or {}
        ident = doc.get("identity") or {}
        markers = ident.get("markers") or {}
        entry: dict = {
            "short": short,
            "emit": {"emit_kind": emit.get("emit_kind")},
            "lab_ids": doc.get("observation_refs") or [],
            "utls_profile": f"utls/{short}.json",
            "status": doc.get("status"),
            "dial": is_dialable(doc),
        }
        if emit.get("uquic_preset"):
            entry["emit"]["uquic_preset"] = emit["uquic_preset"]
        must = []
        must_not = []
        if markers.get("has_0x11"):
            must.append("0x11")
        else:
            must_not.append("0x11")
        if markers.get("has_0x3128"):
            must.append("0x3128")
        else:
            must_not.append("0x3128")
        if markers.get("has_0x20"):
            must.append("0x20")
        expected: dict = {}
        if must:
            expected["tp_id_set_must_contain"] = must
        if must_not:
            expected["tp_id_set_must_not_contain"] = must_not
        if ident.get("scid_len") is not None:
            expected["scid_len"] = ident["scid_len"]
        if ident.get("datagram_count_class") is not None:
            expected["datagrams_typical"] = ident["datagram_count_class"]
        if expected:
            entry["expected"] = expected
        out[short] = entry
    write_json(path, out)


def write_export(docs: list[dict], out: Path) -> dict:
    if out.exists():
        shutil.rmtree(out)
    profiles_dir = out / "profiles"
    profiles_dir.mkdir(parents=True)

    catalog_profiles = []
    aliases: dict[str, str] = {}
    families: dict[str, list[str]] = {}

    for rank, doc in enumerate(sorted(docs, key=lambda d: d["short"])):
        short = doc["short"]
        fam = family_of(doc)
        emit = doc.get("emit") or {}
        auth = doc.get("auth") or {}
        refs = doc.get("observation_refs") or []
        lab_id = refs[0] if refs else short
        dial = is_dialable(doc)

        for alias in doc.get("aliases") or []:
            if alias and alias != short:
                aliases[alias] = short
        families.setdefault(fam, []).append(short)

        entry = {
            "short_name": short,
            "lab_id": lab_id,
            "family": fam,
            "rank": rank,
            "status": doc["status"],
            "dial": dial,
            "emit_kind": emit.get("emit_kind"),
            "auth_capable": bool(auth.get("capable")),
            "format": PROFILE_FORMAT,
            "track": "pinned",
            "builtin": False,
        }
        catalog_profiles.append(entry)

        pdir = profiles_dir / short
        pdir.mkdir(parents=True)
        write_json(pdir / "profile.json", doc)
        write_json(
            pdir / "short.json",
            {
                "short_name": short,
                "lab_id": lab_id,
                "family": fam,
                "rank": rank,
                "status": doc["status"],
                "dial": dial,
                "emit_kind": emit.get("emit_kind"),
                "auth_capable": bool(auth.get("capable")),
                "format": PROFILE_FORMAT,
                "track": "pinned",
            },
        )

    catalog = {
        "version": 1,
        "format": CATALOG_FORMAT,
        "generated_at": sha16_bytes(
            json.dumps(
                {"profiles": catalog_profiles, "aliases": aliases, "families": families},
                sort_keys=True,
            ).encode("utf-8")
        ),
        "profiles": catalog_profiles,
        "aliases": aliases,
        "families": families,
        "notes": (
            "Lab export of QUIC fingerprint catalog (not TCP lxutls). "
            "Future product sync may copy this tree; dial only when dial=true."
        ),
    }
    write_json(out / "catalog.json", catalog)

    lines = [
        "# QUIC fingerprint short names (`quic-utls-profile-v1`)",
        "",
        "| short | family | status | dial | emit_kind | auth | lab_id |",
        "|-------|--------|--------|------|-----------|------|--------|",
    ]
    for p in catalog_profiles:
        lines.append(
            f"| `{p['short_name']}` | {p['family']} | {p['status']} | "
            f"{'yes' if p['dial'] else 'no'} | `{p['emit_kind']}` | "
            f"{'yes' if p['auth_capable'] else 'no'} | `{p['lab_id']}` |"
        )
    lines += [
        "",
        "Lab artifact: `quic/dist/export/`.",
        "Future (out of lab scope): product embed sync — do **not** mix with TCP `lxutls`.",
        "",
    ]
    (out / "NAMES.md").write_bytes(("\n".join(lines)).encode("utf-8"))

    # Keep catalog/emit_templates.json in sync (legacy consumers).
    write_emit_templates(docs, ROOT / "catalog" / "emit_templates.json")
    return catalog


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=EXPORT_DIR)
    ap.add_argument(
        "--sync-first",
        action="store_true",
        help="run sync_utls_catalog.py before export",
    )
    args = ap.parse_args()
    if args.sync_first:
        r = subprocess.run(
            [sys.executable, str(ROOT / "scripts" / "sync_utls_catalog.py")],
            cwd=str(ROOT),
        )
        if r.returncode != 0:
            return r.returncode

    docs = load_curated()
    catalog = write_export(docs, args.out)
    dial_n = sum(1 for p in catalog["profiles"] if p["dial"])
    print(
        f"OK export -> {args.out} profiles={len(catalog['profiles'])} dialable={dial_n}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
